[tool.semantic_release]
version_source = "tag"
version_variable = "src/IfunnyBot/__init__.py:__version__"
branch = "master"
upload_to_pypi = false
upload_to_release = true
changelog_file = "CHANGELOG.md"
commit_parser = "conventional"