[tool.semantic_release]
version_source = "tag"
branch = "master"
upload_to_pypi = false
upload_to_release = true
changelog_file = "CHANGELOG.md"
commit_parser = "conventional"

[tool.semantic_release.plugins]
enabled = [
  "semantic_release.history",
  "semantic_release.version",
  "semantic_release.changelog",
  "semantic_release.commit_parser",
  "semantic_release.github",
  "semantic_release.git"
]